apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamwork-management
spec:
  selector:
    matchLabels:
      app: teamwork-management-application
  replicas: 3
  template:
    metadata:
      labels:
        app: teamwork-management-application
    spec:
      containers:
        - name: teamwork-management
          image: teamwork-management:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mongodb
            - name: DB_NAME  # Setting Database name from configMap
              value: teamwork_management
            - name: DB_USERNAME  # Setting Database username from Secret
              value: root
            - name: DB_PASSWORD # Setting Database password from Secret
              value: root

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: teamwork-management
spec:
  selector:
    app: teamwork-management
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.