# Define a 'Persistent Voulume Claim'(PVC) for Mongo Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: mongodb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---
# Configure 'Deployment' of mongodb server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
    tier: database
spec:
  selector: # mongodb Pod Should contain same labels
    matchLabels:
      app: mongodb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mongodb
        tier: database
    spec:
      containers:
        - image: mongo:latest # image from docker-hub
          name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
            - name: MONGO_INITDB_DATABASE # Setting Database Name from a 'ConfigMap'
              value: teamwork_management
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:        # Mounting voulume obtained from Persistent Volume Claim
            - name: mongodb-persistent-storage
              mountPath: /var/lib/mongodb #This is the path in the container on which the mounting will take place.
      volumes:
        - name: mongodb-persistent-storage # Obtaining 'vloume' from PVC
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
---
# Define a 'Service' To Expose mongodb to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mongodb  # DNS name
  labels:
    app: mongodb
    tier: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:       # mongodb Pod Should contain same labels
    app: mongodb
    tier: database
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant